Feature/mdr_take_out_garbage/state_machine_definition
b-it-bots/mas_domestic_robotics pull request #121
Opened 2019-03-08 16:15 UTC by robertocaiwu

This is a new scenario for the "take out the garbage" task for the German Open. The pull request includes the state machine definition for the task. [See #110] 

Note: The state machine is not completed yet. There are some packages that do not exist yet, and as such the arguments are left empty.

Corrections and suggestions are welcome.

2019-03-10 16:49 UTC, alex-mitrevski commented
@robertocaiwu Do you think this is ready to be merged? If not, could you please add `WIP` to the PR title to indicate that you're still working on it?

2019-03-13 12:58 UTC, robertocaiwu commented
I added the states I considered were missing on the SM. It is ready to be merged now.

2019-03-13 13:03 UTC, alex-mitrevski requested changes

2019-03-13 13:03 UTC, alex-mitrevski commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_take_out_garbage/config/take_out_garbage_sm.yaml
> +              name: start_store_groceries
Copy-paste error - should be `start_take_out_garbage` or something similar...

2019-03-13 13:03 UTC, alex-mitrevski commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_take_out_garbage/config/take_out_garbage_sm.yaml
> +                state: PICK_OBJECT
I think it's better to call this state `PICK_GARBAGE_BAG`.

2019-03-13 13:03 UTC, alex-mitrevski commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_take_out_garbage/config/take_out_garbage_sm.yaml
> +                value: [COLLETION_ZONE]
COLLE**C**TION

2019-03-13 13:03 UTC, alex-mitrevski commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_take_out_garbage/config/take_out_garbage_sm.yaml
> +                state: CHECK_EMPTY_TABLE
`CHECK_EMPTY_TABLE` -> `CHECK_BINS_LEFT`

2019-03-13 13:15 UTC, argenos commented
I just merged #125, for Travis checks to pass, you need the latest changes.

2019-03-13 13:21 UTC, alex-mitrevski approved these changes

2019-03-15 15:42 UTC, argenos commented
The build is failing because the python package is not properly configured, can you take a look?

2019-03-18 14:13 UTC, robertocaiwu commented
I believe this is ready to be merged.

2019-03-18 14:36 UTC, merged