WIP: Adding new robocup scenarios
b-it-bots/mas_domestic_robotics pull request #145
Opened 2019-05-13 20:03 UTC by argenos

We need to clean up as much as possible from the German Open branch before merging to `devel`. I wanted to open the PR to put it in the radar. Whenever you have the time, please add reviews (I'll try to add mine tomorrow); we can decide which things are worth fixing straight away and which merging and opening issues for.

2019-05-17 18:27 UTC, minhnh reviewed
if we will generate all the maps again at the competition, then maybe the `mdr_environments` configs and maps can be removed from merge?

2019-05-17 18:32 UTC, argenos commented
I would keep them. I don't think they hurt and could be used to explain to new members how the arena looks like. It may also be that next year we don't need to remap and only need new poses.

2019-05-17 18:50 UTC, minhnh requested changes
some of the training file should either be tracked by LFS, or added somewhere else: `mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/common/model/current/nlu/training_data.json`

2019-05-17 18:50 UTC, minhnh commented on mdr_hri/mdr_mbot_logger/package.xml
> +  <!-- One maintainer tag required, multiple allowed, one person per tag -->
remove comments

2019-05-17 18:50 UTC, minhnh commented on mdr_hri/mdr_mbot_logger/ros/logs/nlu_logger.txt
> +--- Sentence received: ---
is this file necessary?

2019-05-17 18:50 UTC, minhnh commented on mdr_hri/mdr_mbot_logger/ros/src/mdr_mbot_logger/mbot_logger.py
> +        print('Received sentence ')
change all `print` to `rospy.loginfo` for consistency?

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/CMakeLists.txt
> +
remove comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/scripts/find_people_node
> +                #print('Busy - skipping frame')
debugging comments?

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/action_states.py
> +POINTCLOUD_TOPIC = '/hsrb/head_rgbd_sensor/depth_registered/rectified_points'
HSR specific code, should possibly have a separated launch file in `mas_hsr`.

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/action_states.py
> +            #if i in people_outside_arena:
remove debugging comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
This code should be refactored most likely. `detector` should be moved to `__init__`, with `class_ann_file` loaded as launch parameters, and `detect()` called every time there's a detection request.

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
remove comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/checkpoint
> +model_checkpoint_path: "/home/patrick/rasa/models/current/nlu/intent_classifier_tensorflow_embedding.ckpt"
this should probably be passed as a parameter somewhere

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/package.xml
> +  <!-- One maintainer tag required, multiple allowed, one person per tag -->
clean up comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/training_data.json
> +{
do we really need to add this in the repository?

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_find_my_mates/config/find_my_mates_sm.yaml
> +# Description: Defines a state machine for a RoboCup@Home find my mates scenario
did we ever test this scenario in full?

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
clean up comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/common/model/current/nlu/checkpoint
> +model_checkpoint_path: "/home/kramer/Documents/second_semester/RnD/natural_language_processing/nlu_tools/rasa_nlu/demos/gpsr/models/current/nlu/intent_classifier_tensorflow_embedding.ckpt"
should move this to some generic config file launch param

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/ros/launch/where_is_this.launch
> +    <!-- <include file="$(find mdr_find_people)/ros/launch/find_people.launch" />
clean up comments

2019-05-17 18:50 UTC, minhnh commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/ros/src/mdr_where_is_this/scenario_states/receive_information.py
> +                # # Put relevant intents into a list
clean up comments

2019-05-17 18:56 UTC, minhnh commented
Remapping we will definitely have to redo I think anyway, considering the quality of the map this time and the fact that it will never be similar enough to reuse (we change table, furniture moves around, etc.). Maybe keep just the image for documentation/tutorial, since actual hands-on tasks will probably be done using the C69 map? In any case, I think `go-small-2019` can probably be removed.

2019-05-19 11:00 UTC, alex-mitrevski commented
I agree that `go-small-2019` should be removed. I would also remove the map of the arena (I agree with @minhnh that only a picture would suffice since actual testing is anyway happening with our lab map and it's unlikely that the arena will remain the same next year).

For explaining the arena to new members, I think the models at https://github.com/RoboCupAtHome/GermanOpen2019 are probably more informative anyway.

2019-05-19 11:30 UTC, argenos commented
I’ll remove go-small-2019, but will keep the arena map for testing navigation. It’s the same reason why I would add the rheinbach map here. 

It costs us nothing to keep the maps, and as I said, we might not need to map again next year.

2019-05-19 12:01 UTC, argenos commented on mdr_hri/mdr_mbot_logger/package.xml
> +  <!-- One maintainer tag required, multiple allowed, one person per tag -->
@ErickKramer please clean up the `mdr_mbot_logger` package

2019-05-19 12:28 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/launch/house_keeper_logger.launch
> +    <include file="$(find mdr_mbot_logger)/ros/launch/mbot_logger.launch">
@ErickKramer rename this file, it doesn't seem specific to house keeper, or am I missing something?

2019-05-19 12:28 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/logs/nlu_logger.txt
> +--- Sentence received: ---
This is probably the result of the testing that was done for GPSR. Doesn't belong in `mas_domestic`. But we need a place to push it. @alex-mitrevski we need something like an experiment/result repo, since from this what we want is to analyze what we need to improve for GPSR-like tasks in NLU

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
@minhnh please open an issue for this one, makes sense to tackle it later

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/CMakeLists.txt
> +
@henrikschnor can you take care of this please?

2019-05-19 12:28 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/logs/nlu_logger.txt
> +--- Sentence received: ---
This is probably the result of the testing that was done for GPSR. Doesn't belong in `mas_domestic`. But we need a place to push it. @alex-mitrevski we need something like an experiment/result repo, since from this what we want is to analyze what we need to improve for GPSR-like tasks in NLU. Any thoughts on where to push this to make it accessible to other people in the team?

2019-05-19 12:28 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/launch/house_keeper_logger.launch
> +<?xml version="1.0"?>
@ErickKramer can you rename this one please? Am I missing something or it isn't specific to house keeper?

2019-05-19 12:28 UTC, argenos commented on mdr_hri/mdr_mbot_logger/package.xml
> +  <!-- One maintainer tag required, multiple allowed, one person per tag -->
@ErickKramer can you  take care of this please?

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_perceive_plane_action/ros/src/mdr_perceive_plane_action/action_states.py
> +                    # TODO: handle categories
@minhnh open an issue for this please and remove comment

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/launch/listen.launch
> +        <param name="model_directory" type="str" value="/home/lucy/speech/models/tdnn_en" />
@robertocaiwu this is HSR-specific, can you add an argument and give it a default from `mas_domestic`

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
@PatrickNa can you take care of this one?

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/checkpoint
> +model_checkpoint_path: "/home/patrick/rasa/models/current/nlu/intent_classifier_tensorflow_embedding.ckpt"
@PatrickNa what does this file do?

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
> +_reconstruct
@PatrickNa @henrikschnor there are a bunch of `intent_classifier_*` files in here, do they belong here? 

@minhnh where are we storing models?

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/package.xml
> +  <!-- One maintainer tag required, multiple allowed, one person per tag -->
@PatrickNa can you take care of this?

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/training_data.json
> +{
@ErickKramer @PatrickNa does this belong in the `mas_domestic_datasets` repo? 

@alex-mitrevski perhaps we need a place to store this type of things if they don't belong there.

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_find_my_mates/config/find_my_mates_sm.yaml
> +# Description: Defines a state machine for a RoboCup@Home find my mates scenario
No, but that doesn't matter for the merge

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
I'll take care of this one

2019-05-19 12:28 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/ros/src/mdr_where_is_this/scenario_states/receive_information.py
> +                # # Put relevant intents into a list
@PatrickNa @henrikschnor can you take care of this?

2019-05-19 12:28 UTC, argenos commented on mdr_speech/mdr_speech_matching/common/src/speech_matching/speech_matching.py
> +        objects_dir = os.path.abspath(os.path.join(os.path.dirname( __file__ ), '../..', 'config/objects.txt'))
@PatrickNa I think we need an issue for this one, this probably should come from a parameter so we don't need to hard code it.

2019-05-20 14:20 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
actually, shouldn't this be merged with the `mdr_planning/mdr_actions/mdr_perception_actions/mdr_detect_person` package?

2019-05-20 14:27 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
I don't think they are exactly the same, detecting is pure perception while "finding people" implied some active changes in perspective, as far as I remember

2019-05-20 14:35 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
What Henrick wrote looks like mostly detection to me, though with 3D poses instead of jus RGB images. @henrikschnor could you confirm?

2019-05-21 23:09 UTC, henrikschnor commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
Yes, so far there is just detection of people in the current field of view with the pose of them being calculated from the point cloud. `mdr_detect_person` seems to find bounding boxes for faces in an image, so I'm not sure how they can be merged.

`mdr_find_people` will need to be refactored (or mostly rewritten) anyway, since there are some hardcoded topics and locations and it's still using coco for detection, which I plan to replace with OpenPose and/or some other detection libraries.

2019-05-22 08:28 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
Yeah but `mdr_detect_person` can be extended to have 3D processing, instead of creating a new package. OpenPose and other methods can be added later also to `mdr_detect_person` also.

`mdr_find_people`, I think, will potentially use `mdr_detect_person` for detection but most likely also involve navigation and moving the head, which may need to be made into a more complex skill. It may also be redundant with `find_object` skill, depending on how we implement that.

With that in mind, I think it's a good idea to merge the detection and 3D calculation into `mdr_find_people`. There's a portion which handles inserting the person's info into the knowledge base, however, that may remain here in `mdr_find_people`.

2019-05-22 08:41 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
Going back to my point, this needs further discussion and planning! @minhnh Please open an issue for it.

2019-05-22 12:09 UTC, minhnh commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
> +_reconstruct
Currently I store image detection models using Git LFS in the extension packages (i.e. [`minhnh/mas_image_detection`](https://github.com/minhnh/mas_image_detection) under `models`). We can save them in a separated package/repo (e.g. `mas_models`), however.

2019-05-22 12:14 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
See #152

2019-05-22 12:16 UTC, minhnh commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
I opened #152 for this. Shall we add `mdr_find_people` as it then for this PR?

2019-05-22 12:36 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/CMakeLists.txt
> +## Compile as C++11, supported in ROS Kinetic and newer
Solved in daf6aed

2019-05-22 12:36 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/ros/launch/where_is_this.launch
> +    <!-- <include file="$(find mdr_find_people)/ros/launch/find_people.launch" />
Solved in daf6aed

2019-05-22 12:36 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/ros/src/mdr_where_is_this/scenario_states/receive_information.py
> +                # # Put relevant intents into a list
Solved in daf6aed

2019-05-22 14:08 UTC, argenos commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/find_people.py
> +        detector = SSDKerasObjectDetector(class_file=class_ann_file, model_kwargs_file=kwargs_file)
Except for the cleanup stuff, yes. Refactoring to be done later.

2019-05-24 06:47 UTC, argenos commented
Please note that the deadline to clean up packages is today 18:00, as we discussed last week. 

@henrikschnor please clean up the rasa and mdr_find_people package 
@ErickKramer please clean up the mbot package
@PatrickNa please clean up the mas_hri_bahaviours packages as well as the question matcher

2019-05-24 12:42 UTC, minhnh commented on mdr_hri/mdr_mbot_logger/ros/src/mdr_mbot_logger/mbot_logger.py
> +        # self.pub_sentence_recog = rospy.Publisher('~output_recognition', ActionSlotArray, queue_size=1)
commented out code

2019-05-24 15:17 UTC, PatrickNa approved these changes

2019-05-24 17:36 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/src/mdr_mbot_logger/mbot_logger.py
> +        # to publish the recognition
```suggestion

```

2019-05-24 17:37 UTC, argenos commented on mdr_hri/mdr_mbot_logger/ros/src/mdr_mbot_logger/mbot_logger.py
> +        # self.pub_sentence_recog = rospy.Publisher('~output_recognition', ActionSlotArray, queue_size=1)
```suggestion

```

2019-05-24 22:31 UTC, merged

2019-05-25 12:06 UTC, argenos commented on mdr_speech/mdr_speech_matching/common/src/speech_matching/speech_matching.py
> +        objects_dir = os.path.abspath(os.path.join(os.path.dirname( __file__ ), '../..', 'config/objects.txt'))
There is an issue for this now in #167

2019-05-25 12:08 UTC, argenos commented on mdr_planning/mdr_behaviours/mdr_hri_behaviours/common/models/intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
> +_reconstruct
This should be handled in #171, I've also created the `mas_models` repo.

2019-05-25 12:12 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/launch/listen.launch
> +        <param name="model_directory" type="str" value="/home/lucy/speech/models/tdnn_en" />
I've opened #173 for this.

2019-05-25 12:15 UTC, argenos commented on mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/common/model/current/nlu/checkpoint
> +model_checkpoint_path: "/home/kramer/Documents/second_semester/RnD/natural_language_processing/nlu_tools/rasa_nlu/demos/gpsr/models/current/nlu/intent_classifier_tensorflow_embedding.ckpt"
See #174

2019-05-25 12:22 UTC, argenos commented
I've opened issues for the missing clean up tasks, see #167 #170 #171 #172 #173 #174