WIP: Object Hand Over Action
b-it-bots/mas_domestic_robotics pull request #227
Opened 2020-03-12 13:50 UTC by AhmedFaisal95

# Summary of changes

This pull request contains an implementation of a basic hand-over action used in the research and development project titled: "Incorporating Contextual Knowledge Into Human-Robot Collaborative Task Execution". Please refer to this [technical report](https://pub.h-brs.de/frontdoor/index/index/searchtype/latest/docId/4828/start/9/rows/25) based on the project for more details.

[This video](https://www.youtube.com/watch?v=GguFJ2a7O6E) demonstrates the action in action :).

# TODO before merging

* [ ] Remove unnecessary files
* [ ] Test and validate implementation
* [ ] Clean up code if necessary

2020-03-26 21:54 UTC, alex-mitrevski requested changes

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/README.md
> +An action for handing a grasped object over to a person.
It would be great to expand on the documentation (e.g. following the model of the [pickup action](https://github.com/b-it-bots/mas_domestic_robotics/tree/devel/mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_pickup_action))

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/src/mdr_find_people/action_states.py
> +        self.pointcloud_topic = rospy.get_param("~pointcloud_topic", '/hsrb/head_rgbd_sensor/depth_registered/rectified_points')
This line should be reverted back; the parameter will come from an HSR-specific launch file.

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/ros/launch/hand_over.launch
> +        <param name="gripper_controller_pkg_name" value="mas_hsr_gripper_controller" />
The value should be changed to `mdr_gripper_controller`. We'll have an HSR-specific launch file to set this for the HSR.

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/ros/scripts/hand_over_action
> +        gripper_controller_pkg_name = rospy.get_param('~gripper_controller_pkg_name', 'mas_hsr_gripper_controller')
The default value here should be `mdr_gripper_controller`.

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/ros/src/mdr_hand_over_action/action_states.py
> +                 gripper_controller_pkg_name='mas_hsr_gripper_controller',
Default value `mdr_gripper_controller`

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/ros/src/mdr_hand_over_action/action_states.py
> +                 force_sensor_topic='/hsrb/wrist_wrench/raw',
Use a robot-independent default value, e.g. `/wrench/raw`

2020-03-26 21:54 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_find_people/ros/launch/find_people.launch
> +    <arg name="pointcloud_topic" default="/hsrb/head_rgbd_sensor/depth_registered/rectified_points"/>
This line should be reverted back; the parameter will come from an HSR-specific launch file.

2020-04-10 09:09 UTC, argenos approved these changes

2020-09-25 14:28 UTC, alex-mitrevski requested changes

2020-09-25 14:28 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_hand_over_action/ros/launch/hand_over.launch
> +        <param name="gripper_controller_pkg_name" value="mas_hsr_gripper_controller" />
Leave `mdr_gripper_controller` here please (`mas_hsr_gripper_controller` in the launcher in `mas_hsr`).

2020-09-25 14:28 UTC, alex-mitrevski commented on mdr_planning/mdr_scenarios/mdr_demos/mdr_demo_context_aware_hand_over/ros/launch/hand_over.launch
> +    <include file="$(find mas_hsr_find_people)/ros/launch/find_people.launch" />
Same as above.

2020-10-23 16:45 UTC, alex-mitrevski approved these changes

2020-10-24 05:30 UTC, merged