add functionalities: load class dynamically, test detection service and proxy
b-it-bots/mas_domestic_robotics pull request #29
Opened 2018-04-13 16:02 UTC by minhnh

2018-04-13 16:12 UTC, alex-mitrevski requested changes

2018-04-13 16:12 UTC, alex-mitrevski commented on mdr_perception/mdr_object_recognition/ros/src/mdr_object_recognition/detection_service_proxy.py
> +TEST_DETECTION_SERVICE = '/test_detection_service/execute'
Can you please rename this to "EMPTY_DETECTION_SERVICE" or something like that?

2018-04-13 16:12 UTC, alex-mitrevski commented on mdr_perception/mdr_object_recognition/ros/src/mdr_object_recognition/detection_service_proxy.py
>      @abstractmethod
This decorator should probably be removed; same for the one below.

2018-04-13 16:16 UTC, alex-mitrevski commented
@minhnh In addition to some small changes, we need to improve the documentation of the action. Any of the new actions, e.g. `mdr_pickup_action`, would be a good example.

2018-04-14 11:27 UTC, minhnh commented on mdr_perception/mdr_object_recognition/ros/src/mdr_object_recognition/detection_service_proxy.py
>      @abstractmethod
We sorta need to extend the class anyway since with the dynamic module loading we most likely always call the constructor parameterless. Which is why I kept the abstraction decorator in.

2018-04-15 06:08 UTC, alex-mitrevski requested changes

2018-04-15 06:08 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_perception_actions/mdr_perceive_plane_action/README.md
> +│   │   ├── hsr_detection_service_proxy.py
Remove this please; no HSR-specific things are in this repository.

2018-04-15 06:39 UTC, closed without merging