WIP feature/sound_diagnoser
b-it-bots/mas_domestic_robotics pull request #49
Opened 2018-05-16 16:28 UTC by jcmayoral

Integrating Willlow Garage HRI Sound Library.
Related issue #4

2018-05-16 17:20 UTC, alex-mitrevski commented
Hi @jcmayoral As discussed a while ago, we should't be adding all of these sound files to the repository; only few of them will be used anyway.

We should instead add a set of representative sounds for different robot states, such that we should be able to easily integrate new sounds when we need them.

2018-05-16 18:43 UTC, jcmayoral commented
Hi @alex-mitrevski . Yes, it is my mistake... I would remove the unused files (I forgot the discussion about this issue). The files locations could be changed as well to any location if needed.

About the integration, right now the sound is played each time something is published to a topic defined on a config file so, basically, we can integrate sound just by adding one topic and sound to the config file and of course, the sound file. According to me, this is the easier way.

I will extend this to be able to play a sound adding a dedicated topic to it, probably named sound_monitor or something. 

Another issue that comes to my mind, is the fact that this package must be robot independent. Right now, for playing the sound it relays on the wave and pyaudio libraries that access the perpheral devices (in this case the speaker). Can we do this in the HSR?

2018-05-17 09:27 UTC, argenos commented
I'm unhappy with the name, I would suggest mdr_willow_sounds

2018-05-17 11:39 UTC, jcmayoral commented
If we are not adding addiitonal sounds, I think the name is proper, but not so sure of it over time

2018-05-17 11:41 UTC, argenos commented
If we end up adding new sounds, we can change the name then. Naming it `mdr_willow_sounds` also makes it clear on which library we based this on.

2018-05-17 11:45 UTC, jcmayoral commented
Makes sense I will do the changes

2018-05-17 15:48 UTC, alex-mitrevski commented
I'm not for `mdr_willow_sounds`. The source of the sounds is not important for the package name (and introduces a strong dependency on these particular sounds), but should be acknowledged in the package documentation.

`mdr_sound_communication` would be a better name in my opinion.

2018-05-17 16:16 UTC, argenos commented
I'm fine with that

2018-07-02 10:37 UTC, jcmayoral commented
I do not know yet what do you think about the changes I made some weeks ago

2018-07-02 10:40 UTC, argenos requested changes
I think the last change request was to remove unused sound files, since we don't need all of them. 
The concrete list of sounds from #4 : 
- a greeting (correctly initialized, ready to move)
- started and finished planning (2 different sounds)
- Success or failure of actions (2 sounds) - although not sure about the granularity.
- An error occurred (something that needs manual recovery)
- Emergency stop
- sort of like a honk, to notify people to move away

2018-07-02 10:52 UTC, jcmayoral commented
I already removed several of the file of the willow sound. Indeed, my idea was to preserve on purpose more than the required sounds (there are different voices and sound types on the sound collection), in case they are needed in the future. 

I also have predefined some config files as an example of the use cases (sounds can be changed, I do not trust myself to decide which sounds to be added by default).

However, I will remove the extra sounds and attach the link to the link of the willow sound collection and select some sounds as default.

2018-07-02 10:54 UTC, argenos commented
Due to the amount and size of the files, I think we will add them as we need them. Thanks Jose!

2018-07-02 10:58 UTC, jcmayoral commented
It is the other way around. Thanks to you :D I will do this on the afternoon.

2018-07-03 21:23 UTC, jcmayoral commented
A day later but it is done. Hopefully the size is not a problem anymore.

2018-07-04 18:14 UTC, jcmayoral commented
I got lost with the reviews. What is it missing?

2018-07-07 08:27 UTC, moriarty commented
Why copy any of the Willow Sounds into this repository and rename a sub portion of the original package?

Why not just depend on the original package? Or a fork of the original package?

I think it was by design that Willow Sounds is in it’s own repository: it’s a bunch of binary files and doesn’t need to be mixed with the source code.

This “slimmed down” version of Willow Sounds seems far less general purpose.

Dont you just need to have a bunch of sound recordings somewhere and a configurable mapping to those sound files? If they are coming from the original Willow Sounds, or some slimmed-down fork, or have been translated to some other language shouldn’t matter. At run-time you just need to check if the sound files are there.

2018-07-07 09:05 UTC, jcmayoral commented
Hi Alex. 

I totally agree that that bunch of binary sounds can be stored somewhere and just be called, I have already a fork on the mirror of the repository, I will make it a ROS repository so that can be installed.

However, the original willow sound repository provides 13 different sound collection named from A to M, each of the ones provides the same sound in three different formats. I really think that it must be slimmed down just by the size itself.

2018-07-07 09:29 UTC, jcmayoral commented
This should do the trick . Thanks @moriarty

2018-07-07 18:12 UTC, alex-mitrevski requested changes

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_hri/package.xml
> +<?xml version="1.0"?>
Remove the `mdr_hri` metapackage; it already exists.

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_sound_collections/package.xml
> +<?xml version="1.0"?>
Pleaase rename the sound files so that they have descriptive names...  What are `E01`, `E06`, `E07`, `E09`, and `E12`?

It's fine to add the sounds to a `willow-sounds` directory, **but** use a set of **descriptive** names:
BBeepSuccess.wav -> success.wav
BBeepThinking.wav -> error.wav
BGoAhead.wav -> continue.wav
BHmm.wav -> failure.wav
BPleaseHelp2.wav -> help.wav

I'm still not sure what the purpose of the `EXX` sounds is, but please at least rename them to what you have in the config file:
E01.wav -> receive.wav
E06.wav -> run.wav
E07.wav -> wait.wav
E09.wav -> request.wav
E12.wav -> result.wav

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_sound_collections/package.xml
> +  <maintainer email="jose.mayoral@smail.inf.h-brs.de">Jose Mayoral</maintainer>
Same as for the other package, please change the maintainer tag to `MAS robotics, robotics@inf.h-brs.de`

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_sound_communication/config/topic_config.yaml
> +Hey1:
I think there should be a single topic (of type `std_msgs/String`) to which sound requests are made; the string will have the type of sound to be made.

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_sound_communication/package.xml
> +  <maintainer email="jose.mayoral@smail.inf.h-brs.de">Jose Mayoral</maintainer>
Same as above - please change the maintainer tag.

2018-07-07 18:12 UTC, alex-mitrevski commented on mdr_hri/mdr_sound_communication/ros/src/mdr_sound_communication/sound_communication.py
> +    def dynamic_reconfigureCB(self,config, level):
Please use snake case for the method names **throughout the file**; in this case, you'd have `dynamic_reconfigure_cb`.

2018-07-17 11:22 UTC, argenos submitted a review, later dismissed
Changes look good to me. Just get the approval of @alex-mitrevski

2018-07-17 11:30 UTC, alex-mitrevski commented
I'm fine with everything except for the fact that there are still multiple topics (one per sound) - and their names are `/test`, `/test1`, ... I think it's better to have one topic that takes as input the sound that should be played. This could be a custom message in which the allowed sounds are defined as constants.

2018-07-17 11:41 UTC, jcmayoral commented
Well indeed, there are two ways to play a sound.. one is by publishing to a topic and the other one to subscribe to certain topics that might be relevant. /test , /test1 are just example for that. I found this feature Ok for avoiding modifications on all the nodes. But I will remove the config file, so if needed it could be added.

2018-07-17 11:45 UTC, argenos requested changes

2018-07-17 11:45 UTC, argenos commented on mdr_hri/mdr_sound_communication/config/topic_config.yaml
> +Hey1:
@jcmayoral what we meant is that it's better if instead of a topic per sound, you use a single topic, which contents are "alarm", "failure" or "help".

2018-07-17 11:49 UTC, jcmayoral commented
If I got it well, the topic is already on line 44 of the sound_communication.py

2018-07-17 11:52 UTC, argenos commented
What is being specified in the config file? The contents of the topic?

2018-07-17 11:53 UTC, jcmayoral commented
Yes. 
# Config files examples:

* Monitorable Topics:

<sound_id>:
  topic: <topic_name>
  file: <path_to_sound_in_sound_collection_folder>

* Loading Sound Id without a topic:

<sound_id>: <path_to_sound_in_sound_collection_folder>

2018-07-17 12:09 UTC, argenos commented
Then the key is misleading since it's not the topic we need to publish to, but rather the contents. 
It's also a bit repetitive.
In this case, this might not even be worth a config file, instead, they may just be constants in a custom message. The name of the sound should match that of message contents.

2018-07-30 18:42 UTC, merged