WIP Feature/speech/speech_map_poses to file
b-it-bots/mas_domestic_robotics pull request #55
Opened 2018-06-16 07:34 UTC by jcmayoral

This node provides the functionality to save navigation poses using speech commands

2018-06-16 07:36 UTC, jcmayoral commented
I have one question about this... Since we are already implementing this, does it make sense to have a functionality to update poses?, i.e. there are some situations where a recorded pose must be modified.

2018-06-16 07:38 UTC, jcmayoral commented
As a TODO, the received command must be filtered from "Lucy, save pose <pose_name>"  to <pose_name> so it can be recorded.

2018-06-16 07:40 UTC, jcmayoral commented
HSR related, is there a topic where you can pubiished a sentence to be said by "Lucy"?

2018-06-17 05:14 UTC, alex-mitrevski requested changes

2018-06-17 05:14 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +                tf_listener.waitForTransform('map', '/base_link', rospy.Time.now(), rospy.Duration(1))
I think the frames should be launch file parameters, but `map` and `base_link` should be the default values set in the script (just like in all the actions we have).

2018-06-17 05:14 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/speech_pose_saver.py
> +        rospy.Subscriber("speech_recognizer", String, self.recognizerCB)
The topic should be a launch file parameter; a default value (`recognized_speech`) should be set here in the script though.

2018-06-17 05:14 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +import roslib; roslib.load_manifest('mcr_navigation_tools')
Is this line needed for anything?

2018-06-17 05:14 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_pose_saver/package.xml
> +  <maintainer email="jose.mayoral@smail.inf.h-brs.de">Jose Mayoral</maintainer>
Please add an `author` tag with your name and make `MAS robotics` (robotics@inf.h-brs.de) the maintainer. This eliminates the need for modifying the maintainer tag when there are changes in the team.

2018-06-17 05:14 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +    def setPoseName(self, pose_name):
For this and all other methods: use snake case, not camel case.

2018-06-17 05:20 UTC, alex-mitrevski commented
To your questions:
* Updating poses would be really useful, so I'd say yes.
* We don't publish speech commands directly to a robot's sound topic; instead, we publish a speech request to the `/say` topic and then there's robot-specific functionality which takes care of republishing to the right topic. There's a base class in the `mdr_sound_vocalisation` package for this (which you can find [here](https://github.com/b-it-bots/mas_domestic_robotics/blob/devel/mdr_hri/mdr_sound_vocalisation/ros/src/mdr_sound_vocalisation/sound_vocaliser_base.py)).

2018-06-21 10:42 UTC, jcmayoral commented
Hi Alex... I have one question. I saw one pull request for giving the robot speech navigation commands, does it make sense to create an interface for all the speech command related packages?

2018-06-21 12:02 UTC, alex-mitrevski commented
Hey Jose, I did indeed add this functionality just yesterday. I created a new package for this under `mdr_hri`; the package is called `mdr_command_robot` and currently only has a `spoken_joypad` base class + a node that uses it.

My idea is to indeed use `mdr_command_robot` for organising speech-related functionalities; I suppose it does make sense to actually move your node there.

2018-06-21 12:52 UTC, jcmayoral commented
Ok... I will update this during weekend

2018-06-23 21:16 UTC, alex-mitrevski requested changes

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +        print "Saving Pose"
Please change this to rospy.loginfo

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +                print pose_description
print -> rospy.loginfo

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/speech_pose_saver.py
> +        print ("End")
Please either delete this print statement or change it to something more informative and use rospy.loginfo

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/speech_pose_saver.py
> +        speech_input_topic = rospy.get_param('~speech_input_topic', 'speech_recognizing')
Change the default parameter value to `recognized_speech`

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/package.xml
> +  <maintainer email="jose.mayoral@smail.inf.h-brs.de">Jose Mayoral</maintainer>
As mentioned in my previous review, please change the maintainer tag to `MAS robotics (robotics@inf.h-brs.de)`; this eliminates the need to change the tag if you decide/ever have to leave the team.

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/scripts/speech_pose_saver_node
> +    module = rospy.get_param('module', 'speech_pose_saver')
Please rename `module` to `module_name`

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/scripts/speech_pose_saver_node
> +#!/usr/bin/env python
Add a launcher for the node where all the parameters are passed

2018-06-23 21:16 UTC, alex-mitrevski commented on mdr_hri/mdr_speech_pose_saver/ros/src/mdr_speech_pose_saver/pose_saver.py
> +#!/usr/bin/env python
This implementation has only one functionality missing: the robot needs to ask for confirmation so that we can check that the name of a pose was correctly understood before saving it

2018-06-25 15:52 UTC, jcmayoral commented
Just as a final question... assuming somebody wants to move the robot and record the positions by speech, on the current approach, two nodes must be require. Does it make sense to make a speech master action node and create config files for the required actions? something similar as the node that create state machines. Using importlib library it is possible to import the actions that are needed, and we could use 'eval' to execute the required function. But... I do not know what is the desired future for the speech based actions...

2018-06-27 03:52 UTC, alex-mitrevski commented
I think you're overcomplicating this a bit now. For now, let's keep this independent because it's anyway mostly a convenience functionality. The more serious speech-related components may eventually need something like what you propose, but I think it's a bit too early for that.

2018-07-04 08:43 UTC, jcmayoral commented
I added the confirmation. I tested on my PC :D

2018-07-30 11:02 UTC, merged

2018-07-30 11:03 UTC, alex-mitrevski commented
Merged. Thanks Jose!