Devel
b-it-bots/mas_domestic_robotics pull request #72
Opened 2018-10-11 20:11 UTC by PatrickNa

This pull request adds updates to our speech recognition package. Further, the question matching package has been renewed. The name has been changed to 'speech matching' including also the 
categorization of 'commands'  (additional categories can be easily implemented). The last major contribution is the 'question answering' component. It receives from the speech matching node the question that has been recognized and lets the robot give and answer over the speakers.

This packages are still in their infancy, but the next steps are already planned and can be shared over interested team members easily.

2018-10-12 07:01 UTC, PatrickNa commented
I don't agree with the issues from the Quality Review. Is it a must to resolve them all or can they be discussed?

2018-10-12 09:47 UTC, argenos reviewed
I have not looked at it thoroughly yet, but I removed some of the suggestions. The ones I think we shouldn't ignore I've commented on.

2018-10-12 09:47 UTC, argenos commented on mdr_speech/mdr_speech_matching/common/src/speech_matching/SpeechMatching.py
> +#!/usr/bin/env python
The name of this file should be lower case and joined by underscores.

2018-10-12 09:47 UTC, argenos commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
Why is this being initialized here and not in the constructor?

2018-10-12 11:25 UTC, PatrickNa commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
By initialized you mean the subscriber or the Voice message or both?

2018-10-12 12:06 UTC, argenos commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
why is it outside of the class main() instead of the constructor (__init__).

2018-10-12 12:42 UTC, PatrickNa commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
Good question! I change it in the evening...

2018-10-12 15:36 UTC, argenos commented
This partially addresses https://github.com/b-it-bots/mas_domestic_robotics/issues/47, but leaves out the Answer action, correct?

2018-10-12 15:37 UTC, argenos commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
I think the node initialization and the subscriber belong in the constructor.

2018-10-12 15:39 UTC, argenos commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +    sub = rospy.Subscriber("speech_matcher", MatchedSentence, question_responder.respond)
And this probably belongs in the Answer action instead, so we can merge both

2018-10-12 16:14 UTC, PatrickNa commented
Partially, however I would keep a node version of it, too.

2018-10-12 16:19 UTC, PatrickNa commented
Action answer I will add soon.

2018-10-16 12:51 UTC, argenos submitted a review, later dismissed
I removed one of Codacy's suggestions, but I think we should keep the initialization of the nodes in the constructors instead of in the main function.

2018-10-16 12:51 UTC, argenos commented on mdr_speech/mdr_speech_matching/ros/src/mdr_speech_matching/speech_matcher.py
> +    rospy.init_node("speech_matcher")
These also belong in the constructor.

2018-10-16 12:51 UTC, argenos commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +def main():
These belong in the constructor

2018-10-17 08:26 UTC, alex-mitrevski requested changes

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_answer_action/ros/src/mdr_answer_action/action_states.py
> +        answer_dir = os.path.join(rospack.get_path("mdr_question_answering"), "ros/config/answers.txt")
The package and file name should be passed to the action as arguments (through the launcher and when the action server is created).

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/README.md
> +bool recognize_speech
What is the purpose of this parameter? I don't see it being used anywhere in the action implementation.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/package.xml
> +  <maintainer email="patrick.nagel@smail.inf.h-brs.de">Patrick Nagel</maintainer>
Please change the maintainer tag to
```
<maintainer email="robotics@inf.h-brs.de">MAS robotics</maintainer>
```
This eliminates the need for changing the tag when there are changes to the team.

Make the tags with yours and Roberto's name `author` tags.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +class QuestionResponder():
Inherit from `object` explicitly.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_matching/common/src/speech_matching/speech_matching.py
> +class SpeechMatching():
Inherit from `object` explicitly.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_matching/ros/src/mdr_speech_matching/speech_matcher.py
> +class SpeechMatcher:
Inherit from `object` explicitly.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +class SpeechRecognizer:
Inherit from `object` explicitly.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_matching/package.xml
> +  <maintainer email="patrick.nagel@smail.inf.h-brs.de">Patrick Nagel</maintainer>
Same comment as for `mdr_question_answering`.

2018-10-17 08:26 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +            urllib2.urlopen("http://172.217.21.238", timeout=1)
Why is this IP address hardcoded?

2018-10-17 21:09 UTC, PatrickNa commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +            urllib2.urlopen("http://172.217.21.238", timeout=1)
https://stackoverflow.com/questions/3764291/checking-network-connection

The answer to your question is in the chosen answer. I'm not sure if what the guy refers to is true for us, but I thought, why risk it.

2018-10-17 21:20 UTC, PatrickNa commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/README.md
> +bool recognize_speech
I don't know how to run it without specifying a goal. That's why defined something.

2018-10-17 21:24 UTC, PatrickNa commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_answer_action/ros/src/mdr_answer_action/action_states.py
> +        answer_dir = os.path.join(rospack.get_path("mdr_question_answering"), "ros/config/answers.txt")
There is no launcher yet. I would be happy if this could be considered in an upcoming commit.

2018-10-17 21:28 UTC, PatrickNa commented on mdr_speech/mdr_question_answering/ros/src/mdr_question_answering/question_responder.py
> +class QuestionResponder():
done

2018-10-17 21:29 UTC, PatrickNa commented on mdr_speech/mdr_speech_matching/common/src/speech_matching/speech_matching.py
> +class SpeechMatching():
done

2018-10-17 21:29 UTC, PatrickNa commented on mdr_speech/mdr_speech_matching/ros/src/mdr_speech_matching/speech_matcher.py
> +class SpeechMatcher:
done

2018-10-17 21:29 UTC, PatrickNa commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +class SpeechRecognizer:
done

2018-10-17 21:29 UTC, PatrickNa commented on mdr_speech/mdr_speech_matching/package.xml
> +  <maintainer email="patrick.nagel@smail.inf.h-brs.de">Patrick Nagel</maintainer>
done

2018-10-17 21:29 UTC, PatrickNa commented on mdr_speech/mdr_question_answering/package.xml
> +  <maintainer email="patrick.nagel@smail.inf.h-brs.de">Patrick Nagel</maintainer>
done

2018-10-18 05:26 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/README.md
> +bool recognize_speech
In the message definition, you can just leave the goal part empty (since the dashes delimit the different parts of the definition, there will be nothing above the first set of dashes).

2018-10-18 05:33 UTC, alex-mitrevski commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +            urllib2.urlopen("http://172.217.21.238", timeout=1)
Why not use the snippet that works with `httplib` instead (also in the same post)? That one doesn't require specifying a URL - it's thus more robust - and it works just fine (I've just tested).

2018-10-18 19:36 UTC, PatrickNa commented on mdr_speech/mdr_speech_recognition/ros/src/mdr_speech_recognition/speech_recognizer.py
> +            urllib2.urlopen("http://172.217.21.238", timeout=1)
done

2018-10-19 11:24 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/README.md
> +bool recognize_speech
Can you please remove this from the README?

2018-10-19 11:25 UTC, alex-mitrevski commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_answer_action/package.xml
>    <maintainer email="patrick.nagel@smail.inf.h-brs.de">Patrick Nagel</maintainer>
Just as for the other packages, make this an `author` tag and use

```
<maintainer email="robotics@inf.h-brs.de">MAS robotics</maintainer>
```

for the maintainer tag.

2018-10-19 11:41 UTC, alex-mitrevski approved these changes

2018-10-19 11:42 UTC, merged