Feature/mdr robocup tasks/mdr store groceries
b-it-bots/mas_domestic_robotics pull request #75
Opened 2018-10-19 16:29 UTC by robertocaiwu

listen and process command for storing groceries.

2018-10-23 14:49 UTC, argenos requested changes

2018-10-23 14:49 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/scripts/listen_client_test
> +	rospy.loginfo("usage: listen <duration>")
There is a problem with indentation here I believe

2018-10-23 14:49 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_execute_command_action/ros/action/Execution.action
> +# goal
I know naming discussions are usually a matter of opinion, but in this case I think the action name might cause confusion.  Can you think about a different name and rename it?

2018-10-23 14:49 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_execute_command_action/ros/scripts/execute
> +"""
I think the naming might apply to the rest of the package as well, e.g. this script executes... what?

2018-10-23 14:49 UTC, argenos commented on mdr_speech/mdr_speech_matching/common/config/commands.txt
> +store groceries :
Is this blank on purpose?

2018-10-23 15:26 UTC, robertocaiwu commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/scripts/listen_client_test
> +	rospy.loginfo("usage: listen <duration>")
I checked and there doesn't seem to be an indentation error in my code.

2018-10-23 15:28 UTC, robertocaiwu commented on mdr_speech/mdr_speech_matching/common/config/commands.txt
> +store groceries :
Yes, at the moment, we are not using the phonemes for matching.

2018-10-23 15:52 UTC, argenos commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/scripts/listen_client_test
> +	rospy.loginfo("usage: listen <duration>")
Take a look at the diff in GitHub though, you can clearly select individual spaces on the old version, and only tabs on the new one.

2018-10-24 09:51 UTC, robertocaiwu commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_execute_command_action/ros/action/Execution.action
> +# goal
I renamed it to ProcessSpeech.action

2018-10-24 09:52 UTC, robertocaiwu commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_execute_command_action/ros/scripts/execute
> +"""
Renamed to process_speech_command

2018-10-24 09:53 UTC, robertocaiwu commented on mdr_planning/mdr_actions/mdr_speech_actions/mdr_listen_action/ros/scripts/listen_client_test
> +	rospy.loginfo("usage: listen <duration>")
True, I was using tabs instead of spaces. This is fixed in the latest commit.

2018-10-24 11:26 UTC, alex-mitrevski approved these changes

2018-10-24 11:28 UTC, argenos approved these changes

2018-10-24 11:28 UTC, merged