Feature/speech/weather api
b-it-bots/mas_domestic_robotics pull request #82
Opened 2018-11-02 14:34 UTC by henrikschnor

The questions "how is the weather?" and "where are you?" were answered with hardcoded data (e.g. it's always "sunny"). I implemented the use of free accessible APIs (IP location + Yahoo weather) to answer those questions with actual data. This pull request refers to #79

2018-11-09 20:22 UTC, PatrickNa commented
We have tested the code on the robot today and it held what it promised.

2018-11-10 08:11 UTC, alex-mitrevski requested changes

2018-11-10 08:11 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/common/src/ip_info/ip_info.py
> +class IPInfo:
Please inherit from `object` explicitly.

2018-11-10 08:11 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/common/src/ip_info/ip_info.py
> +            # Something went wrong
It would be useful to at least write the exception message to the console here.

2018-11-10 08:11 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/common/src/weather_api/weather_api.py
> +class WeatherApi:
Please inherit from `object`

2018-11-10 08:11 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/common/src/weather_api/weather_api.py
> +            # Something went wrong
Same here; write the exception message to the console

2018-11-10 08:11 UTC, alex-mitrevski commented on mdr_speech/mdr_question_answering/common/src/weather_api/weather_api.py
> +        return (temperature - 32) * (5/9)
Unfortunately, we generally still use Python 2 for ROS-related activities and in Python 2, the division will result in the integer 0, which is not what you intend here (on the other hand, it will result in a floating-point value in Python 3). Change the division to `(5. / 9.)` to resolve the compatibility issue.

2018-11-10 20:14 UTC, PatrickNa commented on mdr_speech/mdr_question_answering/common/src/weather_api/weather_api.py
> +        return (temperature - 32) * (5/9)
Valid request. Thanks for looking that detailed into it!

2018-11-13 13:45 UTC, henrikschnor commented
@alex-mitrevski Thanks for reviewing the code! I implemented your comments and added another commit for building proper phrases when the condition is not an adjective, so we don't get "it's scattered showers ..." (occured yesterday).

2018-11-13 17:36 UTC, alex-mitrevski commented
OK, this is now ready to be merged. An official welcome to the contributors club for @henrikschnor

2018-11-13 17:37 UTC, alex-mitrevski approved these changes

2018-11-13 17:37 UTC, merged